# Используем официальный образ Python
FROM python:3.12-slim

# Устанавливаем зависимости для компиляции (нужны для psycopg2 и других)
RUN apt-get update && apt-get upgrade -y && apt-get clean

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файлы зависимостей
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код приложения
COPY . .

# Открываем порт, на котором работает FastAPI
EXPOSE 8000

# Команда запуска (через uvicorn)
CMD ["python", "-m", "main"]