"""fix datetime defaults to server_default func.now

Revision ID: 640d08a77405
Revises: 95a7ff1ffd91
Create Date: 2026-04-28 22:39:28.010100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '640d08a77405'
down_revision: Union[str, Sequence[str], None] = '95a7ff1ffd91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.drop_index(op.f('idx_transactions_user_date'), table_name='transactions')
    op.create_index('idx_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False, postgresql_ops={'transaction_date': 'DESC'})
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.drop_index('idx_transactions_user_date', table_name='transactions', postgresql_ops={'transaction_date': 'DESC'})
    op.create_index(op.f('idx_transactions_user_date'), 'transactions', ['user_id', sa.literal_column('transaction_date DESC')], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    # ### end Alembic commands ###
